language: node_js
node_js:
- 8.10.0
after_install:
- "(cd lambda/sacko-bot/ && npm install --production)"
deploy:
- provider: script
  script: node scripts/deploy.js SackoBot
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: node scripts/deploy.js SackoBot dev
  skip_cleanup: true
  on:
    branch: dev
env:
  global:
  - secure: u4wQKteV1i7O3GubD7LLx3YfZY6hIYC9QdyD4qwmza9NEGlb6HW5fcptnvlhAVtm52l8rAwaPv69BmoSOuVZlGY/ygk7i/Z3GJSvtBJiLjCaMIoXOoyl6t5Bo55CPswCqRdFzmwX9XtG/HxD4mTcVn+IU3aR6TML/pjZWJvXcG5IITUogQt48na21ADtGGeYpVEkoAZ91lxN+GJDGgRrTfTJcWW0hceCJ5o+ZLPQZDBD7e3hDs2lDHsXLqQgggRtL0OAN048YSGnwqR/ezHYRTTK1jn2lns5hJEK0Opct1vdRQmcCCKeKaBrrQdGh7Sg0WE0arJf3frjVZbMvwPZ7t2h3F944GKON85iC45RbctMGFTbaOLPEJdIn39JA650Y4f1pY4oR4ev85p25Zaral1fh8O18ViVcI4m16xipczU98JL0Pi6d+GBHcTduqvBmC9Rm7am8A9BdmeEi39SlvvpN8+JrABY5zywxF8654ba9idSE7Q/vG6wHVEPMUs90rYRHbgLMcIyWjgs3/3UeTzEjA6lXZrZOUx98ddNhcLNmGLC0JzcpWmbBJo+pHdxI6OPpj87IAth0jiDqLjRKDaIqXYBHgPfkdzcAO0Q4jI7RgpQLU0OUahxVjPbBXaihLtfOasAPLXBtunMhocm8PGDzPzUt0D+wdTvV7rOsvw=
  - secure: SpHxjx82FCg62ANH5aI4obMcIWlsYSq3yWVfas8j4WQ2fZuoffcXbuAWOjv4rZe0pBqVxuuSmwbf1soIczsOZ6F8965iT8W/rkzNOzAIvIy6x6JJ080Ypa/OVXfgtA948uMb+UVQVbx2JEZjNk3wcwlrcmv+ph2wEXA159IsJ7f0VWGSLEdg8TF1RlAvBbIXb6lVWs5EWZan/MdiTotVVrJseF9udLLAV+Jf1Ht2rv0kiw8+2DGR6C3LZ1fJvnvRsXM8YWcN4gNw9G19uoc5lsknkmRL2n9pwLmCB9FERj77q9YIhBCzoQwimvGkI4gSigIE2H3wZewxf9LxWUd1ZuoURAVdUG5/lADz8mIV2FPIdb7J1uxfwx9npwIzalkz6AesvH4smsLFcKKF34rJyJpQnE/F9oSj7zRuyP/9o7WBP221qF5lHQJiaX3KBzgTU7kOSjy1WC7oJfc3PAvYcT2ZgQf2y4AdH8u+gjYKyOArPUO3AB/rFyfehM7JMLLsyLV9Zf1HHb4TCGQK50qrLilb9012cS6wIIliPKgvR1GB3JEdwBiTH8XJeykE1WlutRthJgFfAtvNi37f/zRGlOFo7q44QTcSa2WneziuTNIgFK47LNZgMQ1GMqqj8BOYH7szOr0Q6KBe3zeRFl+UpQwk6c1Hi3W4HPNrspt711M=
